import turtle
t=turtle.Pen()
x=int(input("enter the width of qube"))
for i in range(1,5):
    t.forward(x)
    t.left(90)
t.left(45)
t.forward(x/3)
t.right(45)
for i in range(1,5):
    t.forward(x)
    t.left(90)
t.left(45)
t.forward(x/3)
t.right(45)
for i in range(1,6):
    t.forward(x)
    t.left(90)

for i in range(1,3):
    t.forward(x)
    t.left(135)
    t.forward(2*x/3)
    t.left(45)
t.left(90)
t.forward(x/2)
t.right(90)
for i in range(1,3):
    t.forward(x)
    t.left(135)
    t.forward(2*x/3)
    t.left(45)
t.left(90)
t.forward(x/2)
t.right(90)
for i in range(1,3):
    t.forward(x)
    t.left(135)
    t.forward(2*x/3)
    t.left(45)
t.forward(x/2)
t.right(90)
for i in range(1,3):
    t.forward(x)
    t.right(135)
    t.forward(2*x/3)
    t.right(45)
t.forward(x/2)
t.right(135)
t.forward(2*x/3)
t.left(180)
t.forward(x/3)
t.right(45)
t.forward(x/2)
t.left(180)
t.forward(x)
t.left(180)
t.forward(x/2)


t.right(90)
t.forward(x/2)
t.left(180)
t.forward(x)
t.up()
t.forward(398)
